Processor branch
slacgismo/solar-data-tools pull request #87
Opened 2022-08-23 21:15 UTC by claireberschauer

Contains pvpro_post_processor.py,  a module containing a class which takes in the output data frame of PVPRO and defines
methods to process the dataset, perform signal decompositions to model degradation trends, analyze how well the models fit, and visualize the trends.

2022-08-26 16:55 UTC, bmeyers commented on solardatatools/pvpro_post_processing.py
> +        # attributes
Attributes that are set by __init__ don't need to be "declared" as None earlier in the function. A typical structure for init would be 

- Run setup code snippets
- Set attributes that will be set by __init__
- "Declare" other attributes as None that will be set by other methods

2022-08-26 16:57 UTC, bmeyers commented on solardatatools/pvpro_post_processing.py
> +    ############################################################################################################
too long

2022-08-26 17:04 UTC, bmeyers commented on solardatatools/pvpro_post_processing.py
> +            cols = [c for c in self.df.columns if 'start' not in c and 'end' not in c and 'mean' not in c and
Logic is backwards. Should be defining based on known keys.

2022-08-26 18:34 UTC, bmeyers requested changes

2022-08-26 18:34 UTC, bmeyers commented on solardatatools/pvpro_post_processing.py
> +            else:
delete lines

2022-08-26 18:34 UTC, bmeyers commented on solardatatools/pvpro_post_processing.py
> +            plt.show()
replace this line with `return plt.gcf()`

2022-08-26 18:34 UTC, bmeyers commented on solardatatools/pvpro_post_processing.py
> +        lambda_4_values = lambda4
`np.atleast_1d(lambda4)`

2022-08-26 18:34 UTC, bmeyers commented on solardatatools/pvpro_post_processing.py
> +        cols = ['system_parameter', 'run_number', 'degradation_model', 'lambda_2_val',
this should come from global dict

2022-08-26 18:34 UTC, bmeyers commented on solardatatools/pvpro_post_processing.py
> +                            if solver is 'Default':
duplicated lines, not necessary

2022-08-26 18:34 UTC, bmeyers commented on solardatatools/pvpro_post_processing.py
> +        ti = time()
please add a comment

2022-08-26 18:34 UTC, bmeyers commented on solardatatools/pvpro_post_processing.py
> +        for label, values in self.df_p.items():
pandas groupby https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html

2022-08-26 18:36 UTC, bmeyers commented
@Thistleman If you get a chance, could you check on why tests are failing on @claireberschauer's branch?

2022-09-14 17:55 UTC, bmeyers commented
Thanks for continuing to clean things up, @claireberschauer! Do you think this is ready for final review and merge?

2022-09-14 17:57 UTC, claireberschauer commented
> 

I think so! Let me know if you want me to make any more edits or if I missed something. Class doesn't start until Tuesday so I have a bit of free time for the next few days.

2022-09-15 22:47 UTC, bmeyers approved these changes

2022-09-15 22:48 UTC, bmeyers commented
This looks great! I'm going to merge it now. I just sent an email about other documents that I'd like to track down before any more time passes. Please let me know if there are any issues.

2022-09-15 22:48 UTC, merged